### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by pjbgf**
Alongside dependencies, the CRDs had to be updated to align with `apiextensions.k8s.io/v1`. 

### Go dependencies
- github.com/blang/semver v3.5.1+incompatible
- github.com/prometheus-operator/prometheus-operator/pkg/apis/monitoring v0.64.0
- github.com/prometheus-operator/prometheus-operator/pkg/client v0.64.0
- github.com/rancher/kubernetes-provider-detector 0.1.5
- github.com/prometheus/client_golang v1.14.0
- github.com/rancher/lasso v0.0.0-20230331223032-f2977a658e8e
- github.com/rancher/security-scan v0.2.11
- github.com/rancher/wrangler v1.1.1
- github.com/sirupsen/logrus v1.9.0
- github.com/urfave/cli v1.22.12
- k8s.io/api v0.26.3
- k8s.io/apiextensions-apiserver v0.26.3
- k8s.io/apimachinery v0.26.3
- k8s.io/client-go v0.26.3

### Other dependencies
- golangci v1.51.2

### CODE REVIEW

**Review by macedogm — APPROVED** [review]

**Comment by macedogm** [comment]
Approved, but we also need a review from @rayandas.

CC @prachidamle @MKlimuszka

**Comment by pjbgf** [comment]
@Akvanvig well spotted on the `jsonPath`, that is now updated. I have also updated all the dependencies. But kept the k8s within the `0.26` minor. PTAL

**Comment by rayandas** [comment]
@pjbgf Thanks for updating the PR. Could you please take a look at the CI about why it’s failing?

**Comment by pjbgf** [comment]
@rayandas that is now fixed, please take another look.

**Comment by pjbgf** [comment]
@rayandas tested changes on this PR alongside https://github.com/rancher/security-scan/pull/111 and https://github.com/rancher/security-scan/pull/109.

The chart version used was `4.0.0` with settings below:

```
affinity: {}
alerts:
  enabled: false
  metricsPort: 8080
  severity: warning
global:
  cattle:
    clusterName: ''
    psp:
      enabled: false
  kubectl:
    repository: rancher/kubectl
    tag: v1.25.6
image:
  cisoperator:
    repository: quay.io/paulinhu/security-scan # this is correct, just for testing purposes
    tag: operator
  securityScan:
    repository: quay.io/paulinhu/security-scan
    tag: cherry
  sonobuoy:
    repository: rancher/mirrored-sonobuoy-sonobuoy
    tag: v0.56.15
nodeSelector: {}
resources: {}
securityScanJob:
  overrideTolerations: false
  tolerations: []
tolerations: []
```

image

**Review by prachidamle — APPROVED** [review]

**Pull request merged**
